apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: confused-imager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whatever
    spec:
      containers:
        - name: something
          image: simpleservice:0.5